-- SQLite
DELETE FROM characterTbl;
INSERT INTO characterTbl (
  symbol,
  keyboardRow,
  keyboardColumn,
  keyWidthMultipler,
  usesSpecialEnterShape,
  keyTextPosition,
  shift,
  finger
)
VALUES
  -- Row 0
  ("¬", 0, 0, null, 0, "top", "right", null),
  ("`", 0, 0, null, 0, "bottom", null, null),
  ("!", 0, 1, null, 0, "top", "right", null),
  ("1", 0, 1, null, 0, "bottom", null, null),
  ('"', 0, 2, null, 0, "top", "right", null),
  ("2", 0, 2, null, 0, "bottom", null, null),
  ("£", 0, 3, null, 0, "top", "right", null),
  ("3", 0, 3, null, 0, "bottom", null, null),
  ("$", 0, 4, null, 0, "top", "right", null),
  ("4", 0, 4, null, 0, "bottom", null, null),
  ("%", 0, 5, null, 0, "top", "right", null),
  ("5", 0, 5, null, 0, "bottom", null, null),
  ("^", 0, 6, null, 0, "top", "right", null),
  ("6", 0, 6, null, 0, "bottom", null, null),
  ("&", 0, 7, null, 0, "top", "right", null),
  ("7", 0, 7, null, 0, "bottom", null, null),
  ("*", 0, 8, null, 0, "top", "right", null),
  ("8", 0, 8, null, 0, "bottom", null, null),
  ("(", 0, 9, null, 0, "top", "right", null),
  ("9", 0, 9, null, 0, "bottom", null, null),
  (")", 0, 10, null, 0, "top", "right", null),
  ("0", 0, 10, null, 0, "bottom", null, null),
  ("_", 0, 11, null, 0, "top", "right", null),
  ("-", 0, 11, null, 0, "bottom", null, null),
  ("+", 0, 12, null, 0, "top", "right", null),
  ("=", 0, 12, null, 0, "bottom", null, null),
  ("backspace", 0, 13, 2, 0, "bottom", null, null),
  -- Row 1
  ("tab", 1, 0, 1.5, 0, "bottom", "right", null),
  ("Q", 1, 1, null, 0, "top", "right", null),
  ("W", 1, 2, null, 0, "top", "right", null),
  ("E", 1, 3, null, 0, "top", "right", null),
  ("R", 1, 4, null, 0, "top", "right", null),
  ("T", 1, 5, null, 0, "top", "right", null),
  ("Y", 1, 6, null, 0, "top", "right", null),
  ("U", 1, 7, null, 0, "top", "right", null),
  ("I", 1, 8, null, 0, "top", "right", null),
  ("O", 1, 9, null, 0, "top", "right", null),
  ("P", 1, 10, null, 0, "top", "right", null),
  ("{", 1, 11, null, 0, "top", "right", null),
  ("[", 1, 11, null, 0, "bottom", null, null),
  ("}", 1, 12, null, 0, "top", "right", null),
  ("]", 1, 12, null, 0, "bottom", null, null),
  ("enter", 1, 13, 1.5, 1, "bottom", null, null),
  -- Row 2
  ("caps", 2, 0, 2, 0, "bottom", null, null),
  ("A", 2, 1, null, 0, "top", "right", null),
  ("S", 2, 2, null, 0, "top", "right", null),
  ("D", 2, 3, null, 0, "top", "right", null),
  ("F", 2, 4, null, 0, "top", "right", null),
  ("G", 2, 5, null, 0, "top", "right", null),
  ("H", 2, 6, null, 0, "top", "right", null),
  ("J", 2, 7, null, 0, "top", "right", null),
  ("K", 2, 8, null, 0, "top", "right", null),
  ("L", 2, 9, null, 0, "top", "right", null),
  (":", 2, 10, null, 0, "top", "right", null),
  (";", 2, 10, null, 0, "bottom", null, null),
  ("@", 2, 11, null, 0, "top", "right", null),
  ("'", 2, 11, null, 0, "bottom", null, null),
  ("~", 2, 12, null, 0, "top", "right", null),
  ("#", 2, 12, null, 0, "bottom", null, null),
  -- Row 3
  ("lshift", 3, 0, 1.25, 0, "bottom", null, null),
  ("|", 3, 1, null, 0, "top", "right", null),
  ("\", 3, 1, null, 0, "bottom", null, null),
  ("Z", 3, 2, null, 0, "top", "right", null),
  ("X", 3, 3, null, 0, "top", "right", null),
  ("C", 3, 4, null, 0, "top", "right", null),
  ("V", 3, 5, null, 0, "top", "right", null),
  ("B", 3, 6, null, 0, "top", "right", null),
  ("N", 3, 7, null, 0, "top", "right", null),
  ("M", 3, 8, null, 0, "top", "right", null),
  ("<", 3, 9, null, 0, "top", "right", null),
  (",", 3, 9, null, 0, "bottom", null, null),
  (">", 3, 10, null, 0, "top", "right", null),
  (".", 3, 10, null, 0, "bottom", null, null),
  ("?", 3, 11, null, 0, "top", "right", null),
  ("/", 3, 11, null, 0, "bottom", null, null),
  ("rshift", 3, 12, 2.75, 0, "bottom", null, null),
  -- Row 4
  ("lctrl", 4, 0, 1.5, 0, "bottom", null, null),
  ("lwin", 4, 1, 1.2, 0, "bottom", null, null),
  ("alt", 4, 2, 1.2, 0, "bottom", null, null),
  ("space", 4, 3, 7.2, 0, "bottom", null, null),
  ("altgr", 4, 9, 1.2, 0, "bottom", null, null),
  ("rwin", 4, 10, 1.2, 0, "bottom", null, null),
  ("rctrl", 4, 12, 1.5, 0, "bottom", null, null);
  -- Lowercase Keys
  -- ("q", null, null, null, 0, null, null, null),
  -- ("w", null, null, null, 0, null, null, null),
  -- ("e", null, null, null, 0, null, null, null),
  -- ("r", null, null, null, 0, null, null, null),
  -- ("t", null, null, null, 0, null, null, null),
  -- ("y", null, null, null, 0, null, null, null),
  -- ("u", null, null, null, 0, null, null, null),
  -- ("i", null, null, null, 0, null, null, null),
  -- ("o", null, null, null, 0, null, null, null),
  -- ("p", null, null, null, 0, null, null, null),
  -- ("a", null, null, null, 0, null, null, null),
  -- ("s", null, null, null, 0, null, null, null),
  -- ("d", null, null, null, 0, null, null, null),
  -- ("f", null, null, null, 0, null, null, null),
  -- ("g", null, null, null, 0, null, null, null),
  -- ("h", null, null, null, 0, null, null, null),
  -- ("j", null, null, null, 0, null, null, null),
  -- ("k", null, null, null, 0, null, null, null),
  -- ("l", null, null, null, 0, null, null, null),
  -- ("z", null, null, null, 0, null, null, null),
  -- ("x", null, null, null, 0, null, null, null),
  -- ("c", null, null, null, 0, null, null, null),
  -- ("v", null, null, null, 0, null, null, null),
  -- ("b", null, null, null, 0, null, null, null),
  -- ("n", null, null, null, 0, null, null, null),
  -- ("m", null, null, null, 0, null, null, null);

